// %% license-end-token %%

//
// This file was generated by Coral RPC.
//
// WARNING: Auto-generated code. Do not modify.
//

#ifndef SCANNERSERVICE_CLIENT_STUB_H
#define SCANNERSERVICE_CLIENT_STUB_H

#include "RpcClientResource.h"
#include "ScannerRpc.pb.h"

namespace ScannerRpc {

class  ScannerServiceClientStub :
public coral::rpc::RpcClientResource {
public:

   explicit ScannerServiceClientStub( coral::rpc::RpcClient &client );
   ~ScannerServiceClientStub();

   void SetMode(
      const Request& request,
      Response& response,
      coral::rpc::AsyncRpcSupervisor* supervisor = NULL ) throw (coral::rpc::RpcException);

}; // End ScannerServiceClientStub

}  // End namespace ScannerRpc

#endif // SCANNERSERVICE_CLIENT_STUB_H
