// %% license-end-token %%

//
// This file was generated by Coral RPC.
//
// WARNING: Auto-generated code. Do not modify.
//

#include "ScannerServiceClientStub.h"

using namespace coral::rpc;
using namespace ScannerRpc;

//-----------------------------------------------------------------------------
ScannerServiceClientStub::ScannerServiceClientStub( RpcClient &client )
   : RpcClientResource( client, "ScannerService" )
{
}

//-----------------------------------------------------------------------------
ScannerServiceClientStub::~ScannerServiceClientStub()
{
}

//-----------------------------------------------------------------------------
void ScannerServiceClientStub::SetMode(
   const Request&    request,
   Response&         response,
   AsyncRpcSupervisor* supervisor ) throw(coral::rpc::RpcException)
{
   if ( call( "SetMode", request, response, supervisor ) == false )
   {
      throw getLastError();
   }
}


