#!/bin/sh

### BEGIN INIT INFO
# Provides:        rpi_scanner
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   5
# Default-Stop: 
# Short-Description: Start RPI scanner daemon 
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/home/scanner/rpi_scanner/server/serial_scanner_service
PIDFILE=/var/run/rpi_scanner.pid

SCANNER_OPTS=" --daemon -p /dev/ttyAMA0"

test -x $DAEMON || exit 5

LOCKFILE=/var/lock/rpiscanner

lock_rpiscanner() {
	if [ -x /usr/bin/lockfile-create ]; then
		lockfile-create $LOCKFILE
		lockfile-touch $LOCKFILE &
		LOCKTOUCHPID="$!"
	fi
}

unlock_rpiscanner() {
	if [ -x /usr/bin/lockfile-create ] ; then
		kill $LOCKTOUCHPID
		lockfile-remove $LOCKFILE
	fi
}

case $1 in
	start)
		log_daemon_msg "Starting RPI Scanner server" "rpiscannerd"
  		start-stop-daemon --start --oknodo --pidfile $PIDFILE --exec $DAEMON -- $SCANNER_OPTS
		status=$?
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping RPI Scanner server" "rpiscannerd"
  		start-stop-daemon --stop --oknodo --pidfile $PIDFILE --remove-pidfile
		log_end_msg $?
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "RPI Scanner server"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
