// %% license-end-token %%

//
// This file was generated by Coral RPC.
//
// WARNING: Auto-generated code. Do not modify.
//

#include "ScannerRpc.pb.h"
#include "ScannerServiceSetModeAction.h"

using namespace coral::rpc;
using namespace ScannerRpc;

//-----------------------------------------------------------------------------
ScannerServiceSetModeAction::ScannerServiceSetModeAction()
   : coral::rpc::RpcServiceAction( "SetMode" )
{
}

//-----------------------------------------------------------------------------
void ScannerServiceSetModeAction::operator() (
   const std::string& request, std::string& response, RpcException& e )
{
   Request request_message;
   Response response_message;

   e.pushFrame( TraceFrame(
      "ScannerServiceSetModeAction",
      "SetMode",
      __FILE__,
      __LINE__
   ));

   request_message.ParseFromString( request );
   if ( request_message.IsInitialized() )
   {
      SetMode( request_message, response_message, e );
      response_message.SerializeToString( &response );
      e.popFrame();
   }
   else
   {
      e.id = MissingParameters;
      e.message = "Parameters not initialized";
   }
}

//-----------------------------------------------------------------------------
void ScannerServiceSetModeAction::SetMode(
   const Request& request,
   Response& response,
   coral::rpc::RpcException& e )
{
   e.id = UnimplementedAction;
   e.message = "ScannerServiceSetModeAction has not been implemented.";
}
