// %% license-end-token %%

//
// This file was generated by Coral RPC.
//
// WARNING: Auto-generated code. Do not modify.
//

#include "ScannerServiceServerStub.h"

using namespace coral::rpc;
using namespace ScannerRpc;

//-----------------------------------------------------------------------------
ScannerServiceServerStub::ScannerServiceServerStub()
   : RpcServerResource("ScannerService")
{
}

//-----------------------------------------------------------------------------
ScannerServiceServerStub::~ScannerServiceServerStub()
{
}

//-----------------------------------------------------------------------------
void ScannerServiceServerStub::registerActions()
{
   addAction( &default_setmode_action_ );
}

